package userauth.database;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

public final class DatabaseInitializer {
    private static final String CREATE_USERS_TABLE = """
            CREATE TABLE IF NOT EXISTS users (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) NOT NULL UNIQUE,
                password VARCHAR(255) NOT NULL,
                full_name VARCHAR(100) NOT NULL,
                email VARCHAR(100) NOT NULL UNIQUE,
                role VARCHAR(20) NOT NULL,
                status VARCHAR(20) NOT NULL,
                created_at BIGINT NOT NULL,
                updated_at BIGINT NOT NULL
            )
            """;

    private static final String CREATE_AUCTIONS_TABLE = """
            CREATE TABLE IF NOT EXISTS auctions (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(200) NOT NULL,
                description TEXT,
                start_price DECIMAL(15, 2) NOT NULL,
                current_highest_bid DECIMAL(15, 2) NOT NULL,
                start_time BIGINT NOT NULL,
                end_time BIGINT NOT NULL,
                category VARCHAR(100),
                image_source TEXT NULL,
                image_data BYTEA NULL,
                created_at BIGINT NOT NULL,
                updated_at BIGINT NOT NULL,
                seller_id INT NOT NULL,
                winner_id INT NULL,
                status VARCHAR(20) NOT NULL,
                anti_sniping_extensions INT NOT NULL DEFAULT 0,
                CONSTRAINT fk_auctions_seller FOREIGN KEY (seller_id) REFERENCES users(id),
                CONSTRAINT fk_auctions_winner FOREIGN KEY (winner_id) REFERENCES users(id)
            )
            """;

    private static final String CREATE_BIDS_TABLE = """
            CREATE TABLE IF NOT EXISTS bids (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                auction_id INT NOT NULL,
                bidder_id INT NOT NULL,
                amount DECIMAL(15, 2) NOT NULL,
                bid_time BIGINT NOT NULL,
                status VARCHAR(20) NOT NULL,
                CONSTRAINT fk_bids_auction FOREIGN KEY (auction_id) REFERENCES auctions(id),
                CONSTRAINT fk_bids_bidder FOREIGN KEY (bidder_id) REFERENCES users(id)
            )
            """;

    private static final String CREATE_HOMEPAGE_ANNOUNCEMENTS_TABLE = """
            CREATE TABLE IF NOT EXISTS homepage_announcements (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title VARCHAR(255) NOT NULL,
                summary TEXT NOT NULL,
                details TEXT,
                schedule_text VARCHAR(255) NOT NULL,
                linked_auction_id INT NULL,
                author_id INT NOT NULL,
                created_at BIGINT NOT NULL,
                updated_at BIGINT NOT NULL,
                CONSTRAINT fk_homepage_author FOREIGN KEY (author_id) REFERENCES users(id),
                CONSTRAINT fk_homepage_linked_auction FOREIGN KEY (linked_auction_id) REFERENCES auctions(id)
            )
            """;
    private static final String CREATE_AUTO_BIDS_TABLE = """
        CREATE TABLE IF NOT EXISTS auto_bids (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            auction_id INT NOT NULL,
            bidder_id INT NOT NULL,
            increment DECIMAL(15, 2) NOT NULL,
            max_price DECIMAL(15, 2) NOT NULL,
            created_at BIGINT NOT NULL,
            updated_at BIGINT NOT NULL,
            CONSTRAINT fk_auto_bids_auction FOREIGN KEY (auction_id) REFERENCES auctions(id),
            CONSTRAINT fk_auto_bids_bidder FOREIGN KEY (bidder_id) REFERENCES users(id)
        )
        """;
    private static final String DROP_AUTO_BID_TRIGGER = "DROP TRIGGER IF EXISTS trigger_auto_bid ON auctions";
    private static final String DROP_AUTO_BID_FUNCTION = "DROP FUNCTION IF EXISTS public.handle_auto_bidding()";
    private static final String ADD_AUCTION_IMAGE_DATA_COLUMN = """
            ALTER TABLE auctions
            ADD COLUMN IF NOT EXISTS image_data BYTEA NULL
            """;
    private static final String ADD_ANTI_SNIPING_EXTENSIONS_COLUMN = """
            ALTER TABLE auctions
            ADD COLUMN IF NOT EXISTS anti_sniping_extensions INT NOT NULL DEFAULT 0
            """;
    private static final String ADD_AUTO_BID_CREATED_AT_COLUMN = """
            ALTER TABLE auto_bids
            ADD COLUMN IF NOT EXISTS created_at BIGINT
            """;
    private static final String ADD_AUTO_BID_UPDATED_AT_COLUMN = """
            ALTER TABLE auto_bids
            ADD COLUMN IF NOT EXISTS updated_at BIGINT
            """;
    private static final String BACKFILL_AUTO_BID_TIMESTAMPS = """
            UPDATE auto_bids
            SET created_at = COALESCE(created_at, id),
                updated_at = COALESCE(updated_at, created_at, id)
            WHERE created_at IS NULL
               OR updated_at IS NULL
            """;
    private static final String DROP_AUTO_BID_RULE_TRIGGER = "DROP TRIGGER IF EXISTS trigger_auto_bid_on_new_rule ON auto_bids";
    private static final String CREATE_AUTO_BIDS_UNIQUE_RULE = """
            CREATE UNIQUE INDEX IF NOT EXISTS ux_auto_bids_auction_bidder
            ON auto_bids (auction_id, bidder_id)
            """;
    private DatabaseInitializer() {
    }

    public static void initialize() {
        DatabaseConfig config = DatabaseConnection.getConfig();
        try {
            if (config.isCreateDatabaseIfMissing()) {
                createDatabaseIfMissing(config.getDatabase());
            }
            createTables();
            synchronizeDatabaseObjects();
            System.out.println(
                    "[Database] Connected to PostgreSQL successfully: " +
                            config.getHost() + ":" + config.getPort() + "/" + config.getDatabase() +
                            " (user: " + config.getUsername() + ")"
            );
        } catch (SQLException ex) {
            throw new IllegalStateException("Unable to initialize the PostgreSQL connection.", ex);
        }
    }

    public static boolean testConnection() {
        try (Connection connection = DatabaseConnection.openDatabaseConnection()) {
            return !connection.isClosed();
        } catch (SQLException ex) {
            return false;
        }
    }

    private static void createDatabaseIfMissing(String databaseName) throws SQLException {
        String safeDatabaseName = databaseName.replace("\"", "\"\"");
        String sql = "CREATE DATABASE \"" + safeDatabaseName + "\"";
        try (Connection connection = DatabaseConnection.openServerConnection();
             Statement statement = connection.createStatement()) {
            try {
                statement.executeUpdate(sql);
            } catch (SQLException ex) {
                if (!"42P04".equals(ex.getSQLState())) {
                    throw ex;
                }
            }
        }
    }

    private static void createTables() throws SQLException {
        List<String> statements = List.of(
                CREATE_USERS_TABLE,
                CREATE_AUCTIONS_TABLE,
                CREATE_BIDS_TABLE,
                CREATE_HOMEPAGE_ANNOUNCEMENTS_TABLE,
                CREATE_AUTO_BIDS_TABLE
        );

        try (Connection connection = DatabaseConnection.openDatabaseConnection();
             Statement statement = connection.createStatement()) {
            for (String sql : statements) {
                statement.executeUpdate(sql);
            }
        }
    }

    private static void synchronizeDatabaseObjects() throws SQLException {
        List<String> statements = List.of(
                ADD_AUCTION_IMAGE_DATA_COLUMN,
                ADD_ANTI_SNIPING_EXTENSIONS_COLUMN,
                ADD_AUTO_BID_CREATED_AT_COLUMN,
                ADD_AUTO_BID_UPDATED_AT_COLUMN,
                BACKFILL_AUTO_BID_TIMESTAMPS,
                CREATE_AUTO_BIDS_UNIQUE_RULE,
                DROP_AUTO_BID_TRIGGER,
                DROP_AUTO_BID_RULE_TRIGGER,
                DROP_AUTO_BID_FUNCTION
        );

        try (Connection connection = DatabaseConnection.openDatabaseConnection();
             Statement statement = connection.createStatement()) {
            for (String sql : statements) {
                statement.executeUpdate(sql);
            }
        }
    }
}
