package userauth.common;

public enum RemoteAction {
    SYSTEM_PING,

    AUTH_REGISTER_GUI,
    AUTH_LOGIN,
    AUTH_GET_ALL_USERS,
    AUTH_CHANGE_PASSWORD,
    AUTH_TOGGLE_USER_STATUS,
    AUTH_DELETE_USER,

    AUCTION_CREATE,
    AUCTION_UPDATE,
    AUCTION_DELETE,
    AUCTION_GET_BY_SELLER,
    AUCTION_GET_ALL,
    AUCTION_GET_BIDS_FOR_AUCTION,
    AUCTION_GET_ALL_BIDS,
    AUCTION_PLACE_BID,
    AUCTION_PLACE_BID_DETAILED,
    AUCTION_CLOSE,
    AUCTION_EXTEND_TIME,
    AUCTION_START_ADMIN_EARLY_CLOSE,
    AUCTION_CANCEL_ADMIN_EARLY_CLOSE,
    AUCTION_GET_ADMIN_EARLY_CLOSE_COUNTDOWNS,

    AUTOBID_CREATE,
    AUTOBID_UPDATE,
    AUTOBID_DELETE,
    AUTOBID_GET_BY_BIDDER,
    AUTOBID_GET_BY_ID,

    HOMEPAGE_GET_ALL,
    HOMEPAGE_SAVE,
    HOMEPAGE_DELETE,

    WALLET_INITIALIZE,
    WALLET_CREATE_TOPUP,
    WALLET_CONFIRM_TOPUP,
    WALLET_CANCEL_TOPUP,
    WALLET_GET_WALLET,
    WALLET_DEDUCT,
    WALLET_ADD,
    WALLET_GET_TOPUP_HISTORY,
    WALLET_GET_ALL_PENDING,
    WALLET_GET_BALANCE
}
