package userauth.database;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

public final class DatabaseInitializer {
    private static final String CREATE_USERS_TABLE = """
            CREATE TABLE IF NOT EXISTS users (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) NOT NULL UNIQUE,
                password VARCHAR(255) NOT NULL,
                full_name VARCHAR(100) NOT NULL,
                email VARCHAR(100) NOT NULL UNIQUE,
                role VARCHAR(20) NOT NULL,
                status VARCHAR(20) NOT NULL,
                created_at BIGINT NOT NULL,
                updated_at BIGINT NOT NULL
            )
            """;

    private static final String CREATE_AUCTIONS_TABLE = """
            CREATE TABLE IF NOT EXISTS auctions (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(200) NOT NULL,
                description TEXT,
                start_price DECIMAL(15, 2) NOT NULL,
                current_highest_bid DECIMAL(15, 2) NOT NULL,
                start_time BIGINT NOT NULL,
                end_time BIGINT NOT NULL,
                category VARCHAR(100),
                image_source TEXT NULL,
                created_at BIGINT NOT NULL,
                updated_at BIGINT NOT NULL,
                seller_id INT NOT NULL,
                winner_id INT NULL,
                status VARCHAR(20) NOT NULL,
                CONSTRAINT fk_auctions_seller FOREIGN KEY (seller_id) REFERENCES users(id),
                CONSTRAINT fk_auctions_winner FOREIGN KEY (winner_id) REFERENCES users(id)
            )
            """;

    private static final String CREATE_BIDS_TABLE = """
            CREATE TABLE IF NOT EXISTS bids (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                auction_id INT NOT NULL,
                bidder_id INT NOT NULL,
                amount DECIMAL(15, 2) NOT NULL,
                bid_time BIGINT NOT NULL,
                status VARCHAR(20) NOT NULL,
                CONSTRAINT fk_bids_auction FOREIGN KEY (auction_id) REFERENCES auctions(id),
                CONSTRAINT fk_bids_bidder FOREIGN KEY (bidder_id) REFERENCES users(id)
            )
            """;

    private static final String CREATE_HOMEPAGE_ANNOUNCEMENTS_TABLE = """
            CREATE TABLE IF NOT EXISTS homepage_announcements (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title VARCHAR(255) NOT NULL,
                summary TEXT NOT NULL,
                details TEXT,
                schedule_text VARCHAR(255) NOT NULL,
                linked_auction_id INT NULL,
                author_id INT NOT NULL,
                created_at BIGINT NOT NULL,
                updated_at BIGINT NOT NULL,
                CONSTRAINT fk_homepage_author FOREIGN KEY (author_id) REFERENCES users(id),
                CONSTRAINT fk_homepage_linked_auction FOREIGN KEY (linked_auction_id) REFERENCES auctions(id)
            )
            """;
    private static final String CREATE_AUTO_BIDS_TABLE = """
        CREATE TABLE IF NOT EXISTS auto_bids (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            auction_id INT NOT NULL,
            bidder_id INT NOT NULL,
            increment DECIMAL(15, 2) NOT NULL,
            max_price DECIMAL(15, 2) NOT NULL,
            CONSTRAINT fk_auto_bids_auction FOREIGN KEY (auction_id) REFERENCES auctions(id),
            CONSTRAINT fk_auto_bids_bidder FOREIGN KEY (bidder_id) REFERENCES users(id)
        )
        """;
    private static final String CREATE_HANDLE_AUTO_BIDDING_FUNCTION = """
            CREATE OR REPLACE FUNCTION public.handle_auto_bidding()
            RETURNS trigger
            LANGUAGE plpgsql
            AS $function$
            declare
              auto_bidder record;
              current_bid numeric;
              current_winner integer;
              next_bid numeric;
              event_time bigint;
            begin
              if TG_OP <> 'UPDATE' then
                return new;
              end if;

              if new.status is distinct from 'RUNNING' then
                return new;
              end if;

              if new.current_highest_bid is not distinct from old.current_highest_bid then
                return new;
              end if;

              current_bid := new.current_highest_bid;
              current_winner := new.winner_id;
              event_time := floor(extract(epoch from clock_timestamp()) * 1000);

              loop
                select bidder_id, max_price, "increment" as bid_increment
                into auto_bidder
                from auto_bids
                where auction_id = new.id
                  and bidder_id <> coalesce(current_winner, -1)
                  and max_price > current_bid
                order by max_price desc, bid_increment desc, bidder_id
                limit 1;

                exit when not found;

                next_bid := least(current_bid + auto_bidder.bid_increment, auto_bidder.max_price);
                exit when next_bid <= current_bid;

                current_bid := next_bid;
                current_winner := auto_bidder.bidder_id;

                insert into bids (auction_id, bidder_id, amount, bid_time, status)
                values (new.id, current_winner, current_bid, event_time, 'ACCEPTED');

                event_time := event_time + 1;
              end loop;

              if current_bid is distinct from new.current_highest_bid
                 or current_winner is distinct from new.winner_id then
                update auctions
                set current_highest_bid = current_bid,
                    winner_id = current_winner,
                    updated_at = event_time
                where id = new.id;
              end if;

              return new;
            end;
            $function$
            """;
    private static final String DROP_AUTO_BID_TRIGGER = "DROP TRIGGER IF EXISTS trigger_auto_bid ON auctions";
    private static final String CREATE_AUTO_BID_TRIGGER = """
            CREATE TRIGGER trigger_auto_bid
            AFTER UPDATE OF current_highest_bid ON auctions
            FOR EACH ROW
            EXECUTE FUNCTION handle_auto_bidding()
            """;
    private DatabaseInitializer() {
    }

    public static void initialize() {
        DatabaseConfig config = DatabaseConnection.getConfig();
        try {
            if (config.isCreateDatabaseIfMissing()) {
                createDatabaseIfMissing(config.getDatabase());
            }
            createTables();
            synchronizeDatabaseObjects();
            System.out.println(
                    "[Database] Connected to PostgreSQL successfully: " +
                            config.getHost() + ":" + config.getPort() + "/" + config.getDatabase() +
                            " (user: " + config.getUsername() + ")"
            );
        } catch (SQLException ex) {
            throw new IllegalStateException("Unable to initialize the PostgreSQL connection.", ex);
        }
    }

    public static boolean testConnection() {
        try (Connection connection = DatabaseConnection.openDatabaseConnection()) {
            return !connection.isClosed();
        } catch (SQLException ex) {
            return false;
        }
    }

    private static void createDatabaseIfMissing(String databaseName) throws SQLException {
        String safeDatabaseName = databaseName.replace("\"", "\"\"");
        String sql = "CREATE DATABASE \"" + safeDatabaseName + "\"";
        try (Connection connection = DatabaseConnection.openServerConnection();
             Statement statement = connection.createStatement()) {
            try {
                statement.executeUpdate(sql);
            } catch (SQLException ex) {
                if (!"42P04".equals(ex.getSQLState())) {
                    throw ex;
                }
            }
        }
    }

    private static void createTables() throws SQLException {
        List<String> statements = List.of(
                CREATE_USERS_TABLE,
                CREATE_AUCTIONS_TABLE,
                CREATE_BIDS_TABLE,
                CREATE_HOMEPAGE_ANNOUNCEMENTS_TABLE,
                CREATE_AUTO_BIDS_TABLE
        );

        try (Connection connection = DatabaseConnection.openDatabaseConnection();
             Statement statement = connection.createStatement()) {
            for (String sql : statements) {
                statement.executeUpdate(sql);
            }
        }
    }

    private static void synchronizeDatabaseObjects() throws SQLException {
        List<String> statements = List.of(
                CREATE_HANDLE_AUTO_BIDDING_FUNCTION,
                DROP_AUTO_BID_TRIGGER,
                CREATE_AUTO_BID_TRIGGER
        );

        try (Connection connection = DatabaseConnection.openDatabaseConnection();
             Statement statement = connection.createStatement()) {
            for (String sql : statements) {
                statement.executeUpdate(sql);
            }
        }
    }
}
