package userauth.database;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

import userauth.util.PasswordUtil;

public final class DatabaseInitializer {
    private static final String CREATE_USERS_TABLE = """
            CREATE TABLE IF NOT EXISTS users (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) NOT NULL UNIQUE,
                password VARCHAR(255) NOT NULL,
                full_name VARCHAR(100) NOT NULL,
                email VARCHAR(100) NOT NULL UNIQUE,
                role VARCHAR(20) NOT NULL,
                status VARCHAR(20) NOT NULL,
                created_at BIGINT NOT NULL,
                updated_at BIGINT NOT NULL
            )
            """;

    private static final String CREATE_AUCTIONS_TABLE = """
            CREATE TABLE IF NOT EXISTS auctions (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(200) NOT NULL,
                description TEXT,
                start_price DECIMAL(15, 2) NOT NULL,
                current_highest_bid DECIMAL(15, 2) NOT NULL,
                start_time BIGINT NOT NULL,
                end_time BIGINT NOT NULL,
                original_end_time BIGINT NOT NULL,
                extension_count INT NOT NULL DEFAULT 0,
                max_extension_count INT NOT NULL DEFAULT 5,
                anti_sniping_enabled BOOLEAN NOT NULL DEFAULT TRUE,
                extension_threshold_seconds INT NOT NULL DEFAULT 30,
                extension_duration_seconds INT NOT NULL DEFAULT 60,
                category VARCHAR(100),
                image_source TEXT NULL,
                created_at BIGINT NOT NULL,
                updated_at BIGINT NOT NULL,
                seller_id INT NOT NULL,
                winner_id INT NULL,
                status VARCHAR(20) NOT NULL,
                CONSTRAINT fk_auctions_seller FOREIGN KEY (seller_id) REFERENCES users(id),
                CONSTRAINT fk_auctions_winner FOREIGN KEY (winner_id) REFERENCES users(id)
            )
            """;

    private static final String CREATE_BIDS_TABLE = """
            CREATE TABLE IF NOT EXISTS bids (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                auction_id INT NOT NULL,
                bidder_id INT NOT NULL,
                amount DECIMAL(15, 2) NOT NULL,
                bid_time BIGINT NOT NULL,
                status VARCHAR(20) NOT NULL,
                CONSTRAINT fk_bids_auction FOREIGN KEY (auction_id) REFERENCES auctions(id),
                CONSTRAINT fk_bids_bidder FOREIGN KEY (bidder_id) REFERENCES users(id)
            )
            """;

    private static final String CREATE_HOMEPAGE_ANNOUNCEMENTS_TABLE = """
            CREATE TABLE IF NOT EXISTS homepage_announcements (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title VARCHAR(255) NOT NULL,
                summary TEXT NOT NULL,
                details TEXT,
                schedule_text VARCHAR(255) NOT NULL,
                linked_auction_id INT NULL,
                author_id INT NOT NULL,
                created_at BIGINT NOT NULL,
                updated_at BIGINT NOT NULL,
                CONSTRAINT fk_homepage_author FOREIGN KEY (author_id) REFERENCES users(id),
                CONSTRAINT fk_homepage_linked_auction FOREIGN KEY (linked_auction_id) REFERENCES auctions(id)
            )
            """;
    private static final String CREATE_AUTO_BIDS_TABLE = """
        CREATE TABLE IF NOT EXISTS auto_bids (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            auction_id INT NOT NULL,
            bidder_id INT NOT NULL,
            increment DECIMAL(15, 2) NOT NULL,
            max_price DECIMAL(15, 2) NOT NULL,
            CONSTRAINT fk_auto_bids_auction FOREIGN KEY (auction_id) REFERENCES auctions(id),
            CONSTRAINT fk_auto_bids_bidder FOREIGN KEY (bidder_id) REFERENCES users(id)
        )
        """;
    private static final String ALTER_AUCTIONS_ADD_ORIGINAL_END_TIME_SQL = """
        ALTER TABLE auctions
        ADD COLUMN IF NOT EXISTS original_end_time BIGINT DEFAULT 0
        """;
    private static final String ALTER_AUCTIONS_ADD_EXTENSION_COUNT_SQL = """
        ALTER TABLE auctions
        ADD COLUMN IF NOT EXISTS extension_count INT NOT NULL DEFAULT 0
        """;
    private static final String ALTER_AUCTIONS_ADD_MAX_EXTENSION_COUNT_SQL = """
        ALTER TABLE auctions
        ADD COLUMN IF NOT EXISTS max_extension_count INT NOT NULL DEFAULT 5
        """;
    private static final String ALTER_AUCTIONS_ADD_ANTI_SNIPING_ENABLED_SQL = """
        ALTER TABLE auctions
        ADD COLUMN IF NOT EXISTS anti_sniping_enabled BOOLEAN NOT NULL DEFAULT TRUE
        """;
    private static final String ALTER_AUCTIONS_ADD_EXTENSION_THRESHOLD_SQL = """
        ALTER TABLE auctions
        ADD COLUMN IF NOT EXISTS extension_threshold_seconds INT NOT NULL DEFAULT 30
        """;
    private static final String ALTER_AUCTIONS_ADD_EXTENSION_DURATION_SQL = """
        ALTER TABLE auctions
        ADD COLUMN IF NOT EXISTS extension_duration_seconds INT NOT NULL DEFAULT 60
        """;
    private static final String BACKFILL_ORIGINAL_END_TIME_SQL = """
        UPDATE auctions
        SET original_end_time = end_time
        WHERE original_end_time = 0
        """;

    private static final String CREATE_WALLETS_TABLE = """
        CREATE TABLE IF NOT EXISTS wallets (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INT NOT NULL UNIQUE,
            balance DECIMAL(15, 2) DEFAULT 0,
            created_at BIGINT NOT NULL,
            updated_at BIGINT NOT NULL,
            CONSTRAINT fk_wallets_user FOREIGN KEY (user_id) REFERENCES users(id)
        )
        """;

    private static final String CREATE_TOPUP_TRANSACTIONS_TABLE = """
        CREATE TABLE IF NOT EXISTS topup_transactions (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INT NOT NULL,
            amount DECIMAL(15, 2) NOT NULL,
            method VARCHAR(50) NOT NULL,
            status VARCHAR(20) NOT NULL,
            reference_code VARCHAR(255),
            transaction_time BIGINT NOT NULL,
            complete_at BIGINT,
            CONSTRAINT fk_topup_transactions_user FOREIGN KEY (user_id) REFERENCES users(id)
        )
        """;
    private static final String CREATE_AUCTIONS_LOOKUP_INDEX_SQL = """
        CREATE INDEX IF NOT EXISTS idx_auctions_seller_status_end_time
        ON auctions (seller_id, status, end_time)
        """;
    private static final String CREATE_BIDS_AUCTION_TIME_INDEX_SQL = """
        CREATE INDEX IF NOT EXISTS idx_bids_auction_time
        ON bids (auction_id, bid_time)
        """;
    private static final String CREATE_BIDS_BIDDER_INDEX_SQL = """
        CREATE INDEX IF NOT EXISTS idx_bids_bidder
        ON bids (bidder_id)
        """;
    private static final String CREATE_AUTOBIDS_AUCTION_INDEX_SQL = """
        CREATE UNIQUE INDEX IF NOT EXISTS idx_auto_bids_auction_bidder
        ON auto_bids (auction_id, bidder_id)
        """;
    private static final String CREATE_TOPUPS_USER_STATUS_INDEX_SQL = """
        CREATE INDEX IF NOT EXISTS idx_topup_transactions_user_status
        ON topup_transactions (user_id, status)
        """;
    private static final String FIND_ANY_ADMIN_SQL = """
        SELECT id
        FROM users
        WHERE role = 'ADMIN'
        LIMIT 1
        """;
    private static final String INSERT_DEFAULT_ADMIN_SQL = """
        INSERT INTO users (username, password, full_name, email, role, status, created_at, updated_at)
        VALUES (?, ?, ?, ?, 'ADMIN', 'ACTIVE', ?, ?)
        """;

    private DatabaseInitializer() {
    }

    public static void initialize() {
        DatabaseConfig config = DatabaseConnection.getConfig();
        try {
            if (config.isCreateDatabaseIfMissing()) {
                createDatabaseIfMissing(config.getDatabase());
            }
            createTables();
        } catch (SQLException ex) {
            throw new IllegalStateException("Unable to initialize the PostgreSQL connection.", ex);
        }
    }

    public static boolean testConnection() {
        try (Connection connection = DatabaseConnection.openDatabaseConnection()) {
            return !connection.isClosed();
        } catch (SQLException ex) {
            return false;
        }
    }

    private static void createDatabaseIfMissing(String databaseName) throws SQLException {
        String safeDatabaseName = databaseName.replace("\"", "\"\"");
        String sql = "CREATE DATABASE \"" + safeDatabaseName + "\"";
        try (Connection connection = DatabaseConnection.openServerConnection();
             Statement statement = connection.createStatement()) {
            try {
                statement.executeUpdate(sql);
            } catch (SQLException ex) {
                if (!"42P04".equals(ex.getSQLState())) {
                    throw ex;
                }
            }
        }
    }

    private static void createTables() throws SQLException {
        List<String> statements = List.of(
                CREATE_USERS_TABLE,
                CREATE_AUCTIONS_TABLE,
                ALTER_AUCTIONS_ADD_ORIGINAL_END_TIME_SQL,
                ALTER_AUCTIONS_ADD_EXTENSION_COUNT_SQL,
                ALTER_AUCTIONS_ADD_MAX_EXTENSION_COUNT_SQL,
                ALTER_AUCTIONS_ADD_ANTI_SNIPING_ENABLED_SQL,
                ALTER_AUCTIONS_ADD_EXTENSION_THRESHOLD_SQL,
                ALTER_AUCTIONS_ADD_EXTENSION_DURATION_SQL,
                BACKFILL_ORIGINAL_END_TIME_SQL,
                CREATE_BIDS_TABLE,
                CREATE_HOMEPAGE_ANNOUNCEMENTS_TABLE,
                CREATE_AUTO_BIDS_TABLE,
                CREATE_WALLETS_TABLE,
                CREATE_TOPUP_TRANSACTIONS_TABLE,
                CREATE_AUCTIONS_LOOKUP_INDEX_SQL,
                CREATE_BIDS_AUCTION_TIME_INDEX_SQL,
                CREATE_BIDS_BIDDER_INDEX_SQL,
                CREATE_AUTOBIDS_AUCTION_INDEX_SQL,
                CREATE_TOPUPS_USER_STATUS_INDEX_SQL
        );

        try (Connection connection = DatabaseConnection.openDatabaseConnection();
             Statement statement = connection.createStatement()) {
            for (String sql : statements) {
                statement.executeUpdate(sql);
            }
            ensureDefaultAdmin(connection);
        }
    }

    private static void ensureDefaultAdmin(Connection connection) throws SQLException {
        try (PreparedStatement findAdmin = connection.prepareStatement(FIND_ANY_ADMIN_SQL);
             ResultSet resultSet = findAdmin.executeQuery()) {
            if (resultSet.next()) {
                return;
            }
        }

        String username = resolveSeedValue("APP_ADMIN_USERNAME", "admin");
        String email = resolveSeedValue("APP_ADMIN_EMAIL", "admin@auction.local");
        String fullName = resolveSeedValue("APP_ADMIN_FULL_NAME", "System Administrator");
        String password = resolveSeedValue("APP_ADMIN_PASSWORD", "Admin123");
        String hashedPassword = PasswordUtil.hashPassword(password);
        long now = System.currentTimeMillis();

        try (PreparedStatement insertAdmin = connection.prepareStatement(INSERT_DEFAULT_ADMIN_SQL)) {
            insertAdmin.setString(1, username);
            insertAdmin.setString(2, hashedPassword);
            insertAdmin.setString(3, fullName);
            insertAdmin.setString(4, email);
            insertAdmin.setLong(5, now);
            insertAdmin.setLong(6, now);
            insertAdmin.executeUpdate();
        }
    }

    private static String resolveSeedValue(String envKey, String defaultValue) {
        String value = System.getenv(envKey);
        if (value == null || value.isBlank()) {
            return defaultValue;
        }
        return value.trim();
    }
}
